### ISSUE TITLE
Database is created but no object store

### ISSUE THREAD

**Issue by SDAdham** [harsh863/ngx-indexed-database#1]
Hi, I installed your package, not sure if I'm the first one ever, but I have an issue with `this._ngxIndexedDBService.createStore(dbName, storeName, storeSchema);`? Is your library working?

**Comment by harsh863** [comment]
hi @SDAdham , can you please share your version and error you are getting?

**Comment by SDAdham** [comment]
Hello @harsh863 , I have already moved to another library, sorry I can no longer provide that but thanks...

**Comment by SDAdham** [comment]
It was probably the latest version by the time I opened this issue.
